//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOA.Framework.SMS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="SMS.SiteMapService")]
    public interface SiteMapService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SiteMapService/FindSiteMapNode", ReplyAction="urn:SiteMapService/FindSiteMapNodeResponse")]
        SOA.Framework.SiteMapHelper.SiteMapItem FindSiteMapNode(string userName, string rawUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SiteMapService/FindSiteMapNodeFromKey", ReplyAction="urn:SiteMapService/FindSiteMapNodeFromKeyResponse")]
        SOA.Framework.SiteMapHelper.SiteMapItem FindSiteMapNodeFromKey(string userName, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SiteMapService/GetRoles", ReplyAction="urn:SiteMapService/GetRolesResponse")]
        string[] GetRoles(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SiteMapService/GetChildNodes", ReplyAction="urn:SiteMapService/GetChildNodesResponse")]
        SOA.Framework.SiteMapHelper.SiteMapItem[] GetChildNodes(string userName, SOA.Framework.SiteMapHelper.SiteMapItem item);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SiteMapService/GetParentNode", ReplyAction="urn:SiteMapService/GetParentNodeResponse")]
        SOA.Framework.SiteMapHelper.SiteMapItem GetParentNode(string userName, SOA.Framework.SiteMapHelper.SiteMapItem item);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SiteMapService/GetSiteMap", ReplyAction="urn:SiteMapService/GetSiteMapResponse")]
        SOA.Framework.SiteMapHelper.SiteMapItem GetSiteMap(string userName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SiteMapServiceChannel : SOA.Framework.SMS.SiteMapService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SiteMapServiceClient : System.ServiceModel.ClientBase<SOA.Framework.SMS.SiteMapService>, SOA.Framework.SMS.SiteMapService {
        
        public SiteMapServiceClient() {
        }
        
        public SiteMapServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SiteMapServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiteMapServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiteMapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOA.Framework.SiteMapHelper.SiteMapItem FindSiteMapNode(string userName, string rawUrl) {
            return base.Channel.FindSiteMapNode(userName, rawUrl);
        }
        
        public SOA.Framework.SiteMapHelper.SiteMapItem FindSiteMapNodeFromKey(string userName, string key) {
            return base.Channel.FindSiteMapNodeFromKey(userName, key);
        }
        
        public string[] GetRoles(string userName) {
            return base.Channel.GetRoles(userName);
        }
        
        public SOA.Framework.SiteMapHelper.SiteMapItem[] GetChildNodes(string userName, SOA.Framework.SiteMapHelper.SiteMapItem item) {
            return base.Channel.GetChildNodes(userName, item);
        }
        
        public SOA.Framework.SiteMapHelper.SiteMapItem GetParentNode(string userName, SOA.Framework.SiteMapHelper.SiteMapItem item) {
            return base.Channel.GetParentNode(userName, item);
        }
        
        public SOA.Framework.SiteMapHelper.SiteMapItem GetSiteMap(string userName) {
            return base.Channel.GetSiteMap(userName);
        }
    }
}
