//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOA.Framework.IS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IS.IImpersonationService")]
    public interface IImpersonationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImpersonationService/RetrieveImpersonatedMFBCodeByUserID", ReplyAction="http://tempuri.org/IImpersonationService/RetrieveImpersonatedMFBCodeByUserIDRespo" +
            "nse")]
        string RetrieveImpersonatedMFBCodeByUserID(long userID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IImpersonationServiceChannel : SOA.Framework.IS.IImpersonationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImpersonationServiceClient : System.ServiceModel.ClientBase<SOA.Framework.IS.IImpersonationService>, SOA.Framework.IS.IImpersonationService {
        
        public ImpersonationServiceClient() {
        }
        
        public ImpersonationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImpersonationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImpersonationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImpersonationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RetrieveImpersonatedMFBCodeByUserID(long userID) {
            return base.Channel.RetrieveImpersonatedMFBCodeByUserID(userID);
        }
    }
}
