//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PANE.Framework.Managed.MfbServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataObject", Namespace="http://schemas.datacontract.org/2004/07/PANE.Framework.DTO")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PANE.Framework.Managed.MfbServiceRef.ActiveDirectory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PANE.Framework.Managed.MfbServiceRef.MfbLogo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PANE.Framework.Managed.MfbServiceRef.State))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PANE.Framework.Managed.MfbServiceRef.CurrencyDenomination))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PANE.Framework.Managed.MfbServiceRef.LGA))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PANE.Framework.Managed.MfbServiceRef.MfbApps))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PANE.Framework.Managed.MfbServiceRef.Mfb))]
    public partial class DataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LogObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MFBCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UseAuditTrailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((this.IsDeletedField.Equals(value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LogObject {
            get {
                return this.LogObjectField;
            }
            set {
                if ((this.LogObjectField.Equals(value) != true)) {
                    this.LogObjectField = value;
                    this.RaisePropertyChanged("LogObject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MFBCode {
            get {
                return this.MFBCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MFBCodeField, value) != true)) {
                    this.MFBCodeField = value;
                    this.RaisePropertyChanged("MFBCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UseAuditTrail {
            get {
                return this.UseAuditTrailField;
            }
            set {
                if ((this.UseAuditTrailField.Equals(value) != true)) {
                    this.UseAuditTrailField = value;
                    this.RaisePropertyChanged("UseAuditTrail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActiveDirectory", Namespace="http://schemas.datacontract.org/2004/07/AppZonePortal.Core.Data")]
    [System.SerializableAttribute()]
    public partial class ActiveDirectory : PANE.Framework.Managed.MfbServiceRef.DataObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADContainerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADServerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PANE.Framework.Managed.MfbServiceRef.Mfb MfbField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADContainer {
            get {
                return this.ADContainerField;
            }
            set {
                if ((object.ReferenceEquals(this.ADContainerField, value) != true)) {
                    this.ADContainerField = value;
                    this.RaisePropertyChanged("ADContainer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADPassword {
            get {
                return this.ADPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.ADPasswordField, value) != true)) {
                    this.ADPasswordField = value;
                    this.RaisePropertyChanged("ADPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADServer {
            get {
                return this.ADServerField;
            }
            set {
                if ((object.ReferenceEquals(this.ADServerField, value) != true)) {
                    this.ADServerField = value;
                    this.RaisePropertyChanged("ADServer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADUsername {
            get {
                return this.ADUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.ADUsernameField, value) != true)) {
                    this.ADUsernameField = value;
                    this.RaisePropertyChanged("ADUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PANE.Framework.Managed.MfbServiceRef.Mfb Mfb {
            get {
                return this.MfbField;
            }
            set {
                if ((object.ReferenceEquals(this.MfbField, value) != true)) {
                    this.MfbField = value;
                    this.RaisePropertyChanged("Mfb");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MfbLogo", Namespace="http://schemas.datacontract.org/2004/07/AppZonePortal.Core.Data")]
    [System.SerializableAttribute()]
    public partial class MfbLogo : PANE.Framework.Managed.MfbServiceRef.DataObject {
        
        private byte[] Imagek__BackingFieldField;
        
        private long MfbIDk__BackingFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Image>k__BackingField", IsRequired=true)]
        public byte[] Imagek__BackingField {
            get {
                return this.Imagek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Imagek__BackingFieldField, value) != true)) {
                    this.Imagek__BackingFieldField = value;
                    this.RaisePropertyChanged("Imagek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<MfbID>k__BackingField", IsRequired=true)]
        public long MfbIDk__BackingField {
            get {
                return this.MfbIDk__BackingFieldField;
            }
            set {
                if ((this.MfbIDk__BackingFieldField.Equals(value) != true)) {
                    this.MfbIDk__BackingFieldField = value;
                    this.RaisePropertyChanged("MfbIDk__BackingField");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="State", Namespace="http://schemas.datacontract.org/2004/07/AppZonePortal.Core.Data")]
    [System.SerializableAttribute()]
    public partial class State : PANE.Framework.Managed.MfbServiceRef.DataObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateName {
            get {
                return this.StateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StateNameField, value) != true)) {
                    this.StateNameField = value;
                    this.RaisePropertyChanged("StateName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CurrencyDenomination", Namespace="http://schemas.datacontract.org/2004/07/AppZonePortal.Core.Data")]
    [System.SerializableAttribute()]
    public partial class CurrencyDenomination : PANE.Framework.Managed.MfbServiceRef.DataObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DenominationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Denomination {
            get {
                return this.DenominationField;
            }
            set {
                if ((this.DenominationField.Equals(value) != true)) {
                    this.DenominationField = value;
                    this.RaisePropertyChanged("Denomination");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LGA", Namespace="http://schemas.datacontract.org/2004/07/AppZonePortal.Core.Data")]
    [System.SerializableAttribute()]
    public partial class LGA : PANE.Framework.Managed.MfbServiceRef.DataObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PANE.Framework.Managed.MfbServiceRef.State StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> StateIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PANE.Framework.Managed.MfbServiceRef.State State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> StateID {
            get {
                return this.StateIDField;
            }
            set {
                if ((this.StateIDField.Equals(value) != true)) {
                    this.StateIDField = value;
                    this.RaisePropertyChanged("StateID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MfbApps", Namespace="http://schemas.datacontract.org/2004/07/AppZonePortal.Core.Data")]
    [System.SerializableAttribute()]
    public partial class MfbApps : PANE.Framework.Managed.MfbServiceRef.DataObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ApplicationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MfbIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PANE.Framework.Managed.MfbServiceRef.Status StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ApplicationID {
            get {
                return this.ApplicationIDField;
            }
            set {
                if ((this.ApplicationIDField.Equals(value) != true)) {
                    this.ApplicationIDField = value;
                    this.RaisePropertyChanged("ApplicationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MfbID {
            get {
                return this.MfbIDField;
            }
            set {
                if ((this.MfbIDField.Equals(value) != true)) {
                    this.MfbIDField = value;
                    this.RaisePropertyChanged("MfbID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PANE.Framework.Managed.MfbServiceRef.Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mfb", Namespace="http://schemas.datacontract.org/2004/07/AppZonePortal.Core.Data")]
    [System.SerializableAttribute()]
    public partial class Mfb : PANE.Framework.Managed.MfbServiceRef.DataObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADContainerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADServerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PANE.Framework.Managed.MfbServiceRef.ActiveDirectory[] ActiveDirectorysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PANE.Framework.Managed.MfbServiceRef.AuthenticationType AuthenticationTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PANE.Framework.Managed.MfbServiceRef.ContactPerson ContactPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CurrentFinancialdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FooterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InstitutionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstitutionCodeStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PANE.Framework.Managed.MfbServiceRef.InstitutionType InstitutionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalConnectionStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PANE.Framework.Managed.MfbServiceRef.MfbLogo LogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MasterCreditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MasterDebitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MasterIncomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Max_CardsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemoteConnectionStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemoteDatabaseNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemotePasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemoteServerIPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemoteUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<PANE.Framework.Managed.MfbServiceRef.MFBStatus> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PANE.Framework.Managed.MfbServiceRef.ValidationType ValidationTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VerveCreditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VerveDebitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VerveIncomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VisaCreditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VisaDebitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VisaIncomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PANE.Framework.Managed.MfbServiceRef.State stateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADContainer {
            get {
                return this.ADContainerField;
            }
            set {
                if ((object.ReferenceEquals(this.ADContainerField, value) != true)) {
                    this.ADContainerField = value;
                    this.RaisePropertyChanged("ADContainer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADPassword {
            get {
                return this.ADPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.ADPasswordField, value) != true)) {
                    this.ADPasswordField = value;
                    this.RaisePropertyChanged("ADPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADServer {
            get {
                return this.ADServerField;
            }
            set {
                if ((object.ReferenceEquals(this.ADServerField, value) != true)) {
                    this.ADServerField = value;
                    this.RaisePropertyChanged("ADServer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADUsername {
            get {
                return this.ADUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.ADUsernameField, value) != true)) {
                    this.ADUsernameField = value;
                    this.RaisePropertyChanged("ADUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PANE.Framework.Managed.MfbServiceRef.ActiveDirectory[] ActiveDirectorys {
            get {
                return this.ActiveDirectorysField;
            }
            set {
                if ((object.ReferenceEquals(this.ActiveDirectorysField, value) != true)) {
                    this.ActiveDirectorysField = value;
                    this.RaisePropertyChanged("ActiveDirectorys");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PANE.Framework.Managed.MfbServiceRef.AuthenticationType AuthenticationType {
            get {
                return this.AuthenticationTypeField;
            }
            set {
                if ((this.AuthenticationTypeField.Equals(value) != true)) {
                    this.AuthenticationTypeField = value;
                    this.RaisePropertyChanged("AuthenticationType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PANE.Framework.Managed.MfbServiceRef.ContactPerson ContactPerson {
            get {
                return this.ContactPersonField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactPersonField, value) != true)) {
                    this.ContactPersonField = value;
                    this.RaisePropertyChanged("ContactPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CurrentFinancialday {
            get {
                return this.CurrentFinancialdayField;
            }
            set {
                if ((this.CurrentFinancialdayField.Equals(value) != true)) {
                    this.CurrentFinancialdayField = value;
                    this.RaisePropertyChanged("CurrentFinancialday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Footer {
            get {
                return this.FooterField;
            }
            set {
                if ((object.ReferenceEquals(this.FooterField, value) != true)) {
                    this.FooterField = value;
                    this.RaisePropertyChanged("Footer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identity {
            get {
                return this.IdentityField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentityField, value) != true)) {
                    this.IdentityField = value;
                    this.RaisePropertyChanged("Identity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InstitutionCode {
            get {
                return this.InstitutionCodeField;
            }
            set {
                if ((this.InstitutionCodeField.Equals(value) != true)) {
                    this.InstitutionCodeField = value;
                    this.RaisePropertyChanged("InstitutionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstitutionCodeString {
            get {
                return this.InstitutionCodeStringField;
            }
            set {
                if ((object.ReferenceEquals(this.InstitutionCodeStringField, value) != true)) {
                    this.InstitutionCodeStringField = value;
                    this.RaisePropertyChanged("InstitutionCodeString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PANE.Framework.Managed.MfbServiceRef.InstitutionType InstitutionType {
            get {
                return this.InstitutionTypeField;
            }
            set {
                if ((this.InstitutionTypeField.Equals(value) != true)) {
                    this.InstitutionTypeField = value;
                    this.RaisePropertyChanged("InstitutionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocalConnectionString {
            get {
                return this.LocalConnectionStringField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalConnectionStringField, value) != true)) {
                    this.LocalConnectionStringField = value;
                    this.RaisePropertyChanged("LocalConnectionString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PANE.Framework.Managed.MfbServiceRef.MfbLogo Logo {
            get {
                return this.LogoField;
            }
            set {
                if ((object.ReferenceEquals(this.LogoField, value) != true)) {
                    this.LogoField = value;
                    this.RaisePropertyChanged("Logo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MasterCredit {
            get {
                return this.MasterCreditField;
            }
            set {
                if ((object.ReferenceEquals(this.MasterCreditField, value) != true)) {
                    this.MasterCreditField = value;
                    this.RaisePropertyChanged("MasterCredit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MasterDebit {
            get {
                return this.MasterDebitField;
            }
            set {
                if ((object.ReferenceEquals(this.MasterDebitField, value) != true)) {
                    this.MasterDebitField = value;
                    this.RaisePropertyChanged("MasterDebit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MasterIncome {
            get {
                return this.MasterIncomeField;
            }
            set {
                if ((object.ReferenceEquals(this.MasterIncomeField, value) != true)) {
                    this.MasterIncomeField = value;
                    this.RaisePropertyChanged("MasterIncome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Max_Cards {
            get {
                return this.Max_CardsField;
            }
            set {
                if ((this.Max_CardsField.Equals(value) != true)) {
                    this.Max_CardsField = value;
                    this.RaisePropertyChanged("Max_Cards");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RemoteConnectionString {
            get {
                return this.RemoteConnectionStringField;
            }
            set {
                if ((object.ReferenceEquals(this.RemoteConnectionStringField, value) != true)) {
                    this.RemoteConnectionStringField = value;
                    this.RaisePropertyChanged("RemoteConnectionString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RemoteDatabaseName {
            get {
                return this.RemoteDatabaseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RemoteDatabaseNameField, value) != true)) {
                    this.RemoteDatabaseNameField = value;
                    this.RaisePropertyChanged("RemoteDatabaseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RemotePassword {
            get {
                return this.RemotePasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.RemotePasswordField, value) != true)) {
                    this.RemotePasswordField = value;
                    this.RaisePropertyChanged("RemotePassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RemoteServerIP {
            get {
                return this.RemoteServerIPField;
            }
            set {
                if ((object.ReferenceEquals(this.RemoteServerIPField, value) != true)) {
                    this.RemoteServerIPField = value;
                    this.RaisePropertyChanged("RemoteServerIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RemoteUsername {
            get {
                return this.RemoteUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.RemoteUsernameField, value) != true)) {
                    this.RemoteUsernameField = value;
                    this.RaisePropertyChanged("RemoteUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortName {
            get {
                return this.ShortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortNameField, value) != true)) {
                    this.ShortNameField = value;
                    this.RaisePropertyChanged("ShortName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<PANE.Framework.Managed.MfbServiceRef.MFBStatus> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PANE.Framework.Managed.MfbServiceRef.ValidationType ValidationType {
            get {
                return this.ValidationTypeField;
            }
            set {
                if ((this.ValidationTypeField.Equals(value) != true)) {
                    this.ValidationTypeField = value;
                    this.RaisePropertyChanged("ValidationType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VerveCredit {
            get {
                return this.VerveCreditField;
            }
            set {
                if ((object.ReferenceEquals(this.VerveCreditField, value) != true)) {
                    this.VerveCreditField = value;
                    this.RaisePropertyChanged("VerveCredit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VerveDebit {
            get {
                return this.VerveDebitField;
            }
            set {
                if ((object.ReferenceEquals(this.VerveDebitField, value) != true)) {
                    this.VerveDebitField = value;
                    this.RaisePropertyChanged("VerveDebit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VerveIncome {
            get {
                return this.VerveIncomeField;
            }
            set {
                if ((object.ReferenceEquals(this.VerveIncomeField, value) != true)) {
                    this.VerveIncomeField = value;
                    this.RaisePropertyChanged("VerveIncome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VisaCredit {
            get {
                return this.VisaCreditField;
            }
            set {
                if ((object.ReferenceEquals(this.VisaCreditField, value) != true)) {
                    this.VisaCreditField = value;
                    this.RaisePropertyChanged("VisaCredit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VisaDebit {
            get {
                return this.VisaDebitField;
            }
            set {
                if ((object.ReferenceEquals(this.VisaDebitField, value) != true)) {
                    this.VisaDebitField = value;
                    this.RaisePropertyChanged("VisaDebit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VisaIncome {
            get {
                return this.VisaIncomeField;
            }
            set {
                if ((object.ReferenceEquals(this.VisaIncomeField, value) != true)) {
                    this.VisaIncomeField = value;
                    this.RaisePropertyChanged("VisaIncome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PANE.Framework.Managed.MfbServiceRef.State state {
            get {
                return this.stateField;
            }
            set {
                if ((object.ReferenceEquals(this.stateField, value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactPerson", Namespace="http://schemas.datacontract.org/2004/07/AppZonePortal.Core.Data")]
    [System.SerializableAttribute()]
    public partial class ContactPerson : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string Emailk__BackingFieldField;
        
        private string FirstNamek__BackingFieldField;
        
        private string LastNamek__BackingFieldField;
        
        private string Phonek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Email>k__BackingField", IsRequired=true)]
        public string Emailk__BackingField {
            get {
                return this.Emailk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Emailk__BackingFieldField, value) != true)) {
                    this.Emailk__BackingFieldField = value;
                    this.RaisePropertyChanged("Emailk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<FirstName>k__BackingField", IsRequired=true)]
        public string FirstNamek__BackingField {
            get {
                return this.FirstNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNamek__BackingFieldField, value) != true)) {
                    this.FirstNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("FirstNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<LastName>k__BackingField", IsRequired=true)]
        public string LastNamek__BackingField {
            get {
                return this.LastNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNamek__BackingFieldField, value) != true)) {
                    this.LastNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("LastNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Phone>k__BackingField", IsRequired=true)]
        public string Phonek__BackingField {
            get {
                return this.Phonek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Phonek__BackingFieldField, value) != true)) {
                    this.Phonek__BackingFieldField = value;
                    this.RaisePropertyChanged("Phonek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationType", Namespace="http://schemas.datacontract.org/2004/07/AppZonePortal.Core.Utility")]
    public enum AuthenticationType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        System = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ActiveDirectory = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InstitutionType", Namespace="http://schemas.datacontract.org/2004/07/AppZonePortal.Core.Utility")]
    public enum InstitutionType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MFB = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CorrespondentBank = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mobile = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MFBStatus", Namespace="http://schemas.datacontract.org/2004/07/AppZonePortal.Core.Utility")]
    public enum MFBStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Migration = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InActive = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationType", Namespace="http://schemas.datacontract.org/2004/07/AppZonePortal.Core.Utility")]
    public enum ValidationType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        No = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yes = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/PANE.Framework.Managed.Functions.DTO")]
    public enum Status : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InActive = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MfbServiceRef.IMfbService")]
    public interface IMfbService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMfbService/GetBySwitchCode", ReplyAction="http://tempuri.org/IMfbService/GetBySwitchCodeResponse")]
        PANE.Framework.Managed.MfbServiceRef.Mfb GetBySwitchCode(string switchCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMfbService/RetrieveAllStates", ReplyAction="http://tempuri.org/IMfbService/RetrieveAllStatesResponse")]
        PANE.Framework.Managed.MfbServiceRef.State[] RetrieveAllStates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMfbService/RetrieveAllDenominations", ReplyAction="http://tempuri.org/IMfbService/RetrieveAllDenominationsResponse")]
        PANE.Framework.Managed.MfbServiceRef.CurrencyDenomination[] RetrieveAllDenominations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMfbService/GetImageUrl", ReplyAction="http://tempuri.org/IMfbService/GetImageUrlResponse")]
        string GetImageUrl(string mfbCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMfbService/GetLGAByID", ReplyAction="http://tempuri.org/IMfbService/GetLGAByIDResponse")]
        PANE.Framework.Managed.MfbServiceRef.LGA GetLGAByID(long LGAID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMfbService/GetLGAsByStateID", ReplyAction="http://tempuri.org/IMfbService/GetLGAsByStateIDResponse")]
        PANE.Framework.Managed.MfbServiceRef.LGA[] GetLGAsByStateID(long stateID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMfbService/RetrieveAll", ReplyAction="http://tempuri.org/IMfbService/RetrieveAllResponse")]
        PANE.Framework.Managed.MfbServiceRef.Mfb[] RetrieveAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMfbService/GetByID", ReplyAction="http://tempuri.org/IMfbService/GetByIDResponse")]
        PANE.Framework.Managed.MfbServiceRef.Mfb GetByID(long mfbID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMfbService/GetByInstitutionCode", ReplyAction="http://tempuri.org/IMfbService/GetByInstitutionCodeResponse")]
        PANE.Framework.Managed.MfbServiceRef.Mfb GetByInstitutionCode(string InstitutionCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMfbService/GetByCode", ReplyAction="http://tempuri.org/IMfbService/GetByCodeResponse")]
        PANE.Framework.Managed.MfbServiceRef.Mfb GetByCode(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMfbService/GetByIDs", ReplyAction="http://tempuri.org/IMfbService/GetByIDsResponse")]
        System.Collections.Generic.Dictionary<long, PANE.Framework.Managed.MfbServiceRef.Mfb> GetByIDs(long[] mfbIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMfbService/GetPortByMacAddress", ReplyAction="http://tempuri.org/IMfbService/GetPortByMacAddressResponse")]
        int GetPortByMacAddress(string macAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMfbService/AllMfbsExcluding", ReplyAction="http://tempuri.org/IMfbService/AllMfbsExcludingResponse")]
        PANE.Framework.Managed.MfbServiceRef.Mfb[] AllMfbsExcluding(long[] mfbIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMfbService/GetMfbAppUsingMfbCode", ReplyAction="http://tempuri.org/IMfbService/GetMfbAppUsingMfbCodeResponse")]
        PANE.Framework.Managed.MfbServiceRef.MfbApps GetMfbAppUsingMfbCode(long appID, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMfbService/ChangeFinancialDate", ReplyAction="http://tempuri.org/IMfbService/ChangeFinancialDateResponse")]
        bool ChangeFinancialDate(string mfbCode, System.DateTime newFinancialDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMfbService/GetMFBLogoByID", ReplyAction="http://tempuri.org/IMfbService/GetMFBLogoByIDResponse")]
        PANE.Framework.Managed.MfbServiceRef.MfbLogo GetMFBLogoByID(long mfbID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMfbService/GetByInstitutionID", ReplyAction="http://tempuri.org/IMfbService/GetByInstitutionIDResponse")]
        PANE.Framework.Managed.MfbServiceRef.MfbApps[] GetByInstitutionID(long institutionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMfbService/GetApplicationIDs", ReplyAction="http://tempuri.org/IMfbService/GetApplicationIDsResponse")]
        long[] GetApplicationIDs(string code);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMfbServiceChannel : PANE.Framework.Managed.MfbServiceRef.IMfbService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MfbServiceClient : System.ServiceModel.ClientBase<PANE.Framework.Managed.MfbServiceRef.IMfbService>, PANE.Framework.Managed.MfbServiceRef.IMfbService {
        
        public MfbServiceClient() {
        }
        
        public MfbServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MfbServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MfbServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MfbServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PANE.Framework.Managed.MfbServiceRef.Mfb GetBySwitchCode(string switchCode) {
            return base.Channel.GetBySwitchCode(switchCode);
        }
        
        public PANE.Framework.Managed.MfbServiceRef.State[] RetrieveAllStates() {
            return base.Channel.RetrieveAllStates();
        }
        
        public PANE.Framework.Managed.MfbServiceRef.CurrencyDenomination[] RetrieveAllDenominations() {
            return base.Channel.RetrieveAllDenominations();
        }
        
        public string GetImageUrl(string mfbCode) {
            return base.Channel.GetImageUrl(mfbCode);
        }
        
        public PANE.Framework.Managed.MfbServiceRef.LGA GetLGAByID(long LGAID) {
            return base.Channel.GetLGAByID(LGAID);
        }
        
        public PANE.Framework.Managed.MfbServiceRef.LGA[] GetLGAsByStateID(long stateID) {
            return base.Channel.GetLGAsByStateID(stateID);
        }
        
        public PANE.Framework.Managed.MfbServiceRef.Mfb[] RetrieveAll() {
            return base.Channel.RetrieveAll();
        }
        
        public PANE.Framework.Managed.MfbServiceRef.Mfb GetByID(long mfbID) {
            return base.Channel.GetByID(mfbID);
        }
        
        public PANE.Framework.Managed.MfbServiceRef.Mfb GetByInstitutionCode(string InstitutionCode) {
            return base.Channel.GetByInstitutionCode(InstitutionCode);
        }
        
        public PANE.Framework.Managed.MfbServiceRef.Mfb GetByCode(string code) {
            return base.Channel.GetByCode(code);
        }
        
        public System.Collections.Generic.Dictionary<long, PANE.Framework.Managed.MfbServiceRef.Mfb> GetByIDs(long[] mfbIDs) {
            return base.Channel.GetByIDs(mfbIDs);
        }
        
        public int GetPortByMacAddress(string macAddress) {
            return base.Channel.GetPortByMacAddress(macAddress);
        }
        
        public PANE.Framework.Managed.MfbServiceRef.Mfb[] AllMfbsExcluding(long[] mfbIDs) {
            return base.Channel.AllMfbsExcluding(mfbIDs);
        }
        
        public PANE.Framework.Managed.MfbServiceRef.MfbApps GetMfbAppUsingMfbCode(long appID, string code) {
            return base.Channel.GetMfbAppUsingMfbCode(appID, code);
        }
        
        public bool ChangeFinancialDate(string mfbCode, System.DateTime newFinancialDate) {
            return base.Channel.ChangeFinancialDate(mfbCode, newFinancialDate);
        }
        
        public PANE.Framework.Managed.MfbServiceRef.MfbLogo GetMFBLogoByID(long mfbID) {
            return base.Channel.GetMFBLogoByID(mfbID);
        }
        
        public PANE.Framework.Managed.MfbServiceRef.MfbApps[] GetByInstitutionID(long institutionID) {
            return base.Channel.GetByInstitutionID(institutionID);
        }
        
        public long[] GetApplicationIDs(string code) {
            return base.Channel.GetApplicationIDs(code);
        }
    }
}
