//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOA.Framework.AS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataObject", Namespace="http://schemas.datacontract.org/2004/07/PANE.Framework.DTO")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOA.Framework.AS.Approval))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOA.Framework.AS.UserRole))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOA.Framework.AS.ApprovalConfiguration))]
    public partial class DataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LogObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MFBCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UseAuditTrailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((this.IsDeletedField.Equals(value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LogObject {
            get {
                return this.LogObjectField;
            }
            set {
                if ((this.LogObjectField.Equals(value) != true)) {
                    this.LogObjectField = value;
                    this.RaisePropertyChanged("LogObject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MFBCode {
            get {
                return this.MFBCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MFBCodeField, value) != true)) {
                    this.MFBCodeField = value;
                    this.RaisePropertyChanged("MFBCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UseAuditTrail {
            get {
                return this.UseAuditTrailField;
            }
            set {
                if ((this.UseAuditTrailField.Equals(value) != true)) {
                    this.UseAuditTrailField = value;
                    this.RaisePropertyChanged("UseAuditTrail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Approval", Namespace="http://schemas.datacontract.org/2004/07/AppZonePortal.Core.Data")]
    [System.SerializableAttribute()]
    public partial class Approval : SOA.Framework.AS.DataObject {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRole", Namespace="http://schemas.datacontract.org/2004/07/PANE.Framework.Functions.DTO")]
    [System.SerializableAttribute()]
    public partial class UserRole : SOA.Framework.AS.DataObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOA.Framework.AS.UserRoleScope ScopeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOA.Framework.AS.UserCategory UserCategoryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOA.Framework.AS.UserRoleScope Scope {
            get {
                return this.ScopeField;
            }
            set {
                if ((this.ScopeField.Equals(value) != true)) {
                    this.ScopeField = value;
                    this.RaisePropertyChanged("Scope");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOA.Framework.AS.UserCategory UserCategory {
            get {
                return this.UserCategoryField;
            }
            set {
                if ((this.UserCategoryField.Equals(value) != true)) {
                    this.UserCategoryField = value;
                    this.RaisePropertyChanged("UserCategory");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApprovalConfiguration", Namespace="http://schemas.datacontract.org/2004/07/PANE.Framework.Approval.DTO")]
    [System.SerializableAttribute()]
    public partial class ApprovalConfiguration : SOA.Framework.AS.DataObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOA.Framework.AS.UserRole ApprovingRoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ApprovingRoleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsApprovableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakeRoleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MakerRoleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationName {
            get {
                return this.ApplicationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationNameField, value) != true)) {
                    this.ApplicationNameField = value;
                    this.RaisePropertyChanged("ApplicationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOA.Framework.AS.UserRole ApprovingRole {
            get {
                return this.ApprovingRoleField;
            }
            set {
                if ((object.ReferenceEquals(this.ApprovingRoleField, value) != true)) {
                    this.ApprovingRoleField = value;
                    this.RaisePropertyChanged("ApprovingRole");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ApprovingRoleID {
            get {
                return this.ApprovingRoleIDField;
            }
            set {
                if ((this.ApprovingRoleIDField.Equals(value) != true)) {
                    this.ApprovingRoleIDField = value;
                    this.RaisePropertyChanged("ApprovingRoleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsApprovable {
            get {
                return this.IsApprovableField;
            }
            set {
                if ((this.IsApprovableField.Equals(value) != true)) {
                    this.IsApprovableField = value;
                    this.RaisePropertyChanged("IsApprovable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MakeRoleName {
            get {
                return this.MakeRoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MakeRoleNameField, value) != true)) {
                    this.MakeRoleNameField = value;
                    this.RaisePropertyChanged("MakeRoleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MakerRole {
            get {
                return this.MakerRoleField;
            }
            set {
                if ((this.MakerRoleField.Equals(value) != true)) {
                    this.MakerRoleField = value;
                    this.RaisePropertyChanged("MakerRole");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRoleScope", Namespace="http://schemas.datacontract.org/2004/07/PANE.Framework.Managed.Functions.DTO")]
    public enum UserRoleScope : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Branch = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Region = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Global = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserCategory", Namespace="http://schemas.datacontract.org/2004/07/PANE.Framework.Managed.Functions.DTO")]
    public enum UserCategory : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServiceProvider = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mfb = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CorrespondentBank = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Customer = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrailItem", Namespace="http://schemas.datacontract.org/2004/07/PANE.Framework.Utility")]
    [System.SerializableAttribute()]
    public partial class TrailItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueAfterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueBeforeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValueAfter {
            get {
                return this.ValueAfterField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueAfterField, value) != true)) {
                    this.ValueAfterField = value;
                    this.RaisePropertyChanged("ValueAfter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValueBefore {
            get {
                return this.ValueBeforeField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueBeforeField, value) != true)) {
                    this.ValueBeforeField = value;
                    this.RaisePropertyChanged("ValueBefore");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AS.IApprovalConfigService")]
    public interface IApprovalConfigService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApprovalConfigService/RetrieveApprovalConfiguration", ReplyAction="http://tempuri.org/IApprovalConfigService/RetrieveApprovalConfigurationResponse")]
        SOA.Framework.AS.ApprovalConfiguration RetrieveApprovalConfiguration(string mfbCode, long functionID, string appName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApprovalConfigService/CreateEditApproval", ReplyAction="http://tempuri.org/IApprovalConfigService/CreateEditApprovalResponse")]
        SOA.Framework.AS.Approval CreateEditApproval(string mfbCode, string dataType, string entityName, long objectID, long functionID, byte[] dataBefore, byte[] dataAfter, string appName, string appEndPoint, long currentUserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApprovalConfigService/CreateAddApproval", ReplyAction="http://tempuri.org/IApprovalConfigService/CreateAddApprovalResponse")]
        SOA.Framework.AS.Approval CreateAddApproval(string mfbCode, string dataType, string entityName, long objectID, long functionID, byte[] newData, string appName, string appEndPoint, long currentUserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApprovalConfigService/CreateDeleteApproval", ReplyAction="http://tempuri.org/IApprovalConfigService/CreateDeleteApprovalResponse")]
        SOA.Framework.AS.Approval CreateDeleteApproval(string mfbCode, string dataType, string entityName, long objectID, long functionID, byte[] dataToDelete, string appName, string appEndPoint, long currentUserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApprovalConfigService/RetrieveByMakerRoleName", ReplyAction="http://tempuri.org/IApprovalConfigService/RetrieveByMakerRoleNameResponse")]
        bool RetrieveByMakerRoleName(string mfbCode, string makerRoleName, long functionID, string appName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApprovalConfigService/GetApprovalObject", ReplyAction="http://tempuri.org/IApprovalConfigService/GetApprovalObjectResponse")]
        SOA.Framework.AS.TrailItem[] GetApprovalObject(byte[] dataBefore, byte[] dataAfter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IApprovalConfigServiceChannel : SOA.Framework.AS.IApprovalConfigService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApprovalConfigServiceClient : System.ServiceModel.ClientBase<SOA.Framework.AS.IApprovalConfigService>, SOA.Framework.AS.IApprovalConfigService {
        
        public ApprovalConfigServiceClient() {
        }
        
        public ApprovalConfigServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApprovalConfigServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApprovalConfigServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApprovalConfigServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOA.Framework.AS.ApprovalConfiguration RetrieveApprovalConfiguration(string mfbCode, long functionID, string appName) {
            return base.Channel.RetrieveApprovalConfiguration(mfbCode, functionID, appName);
        }
        
        public SOA.Framework.AS.Approval CreateEditApproval(string mfbCode, string dataType, string entityName, long objectID, long functionID, byte[] dataBefore, byte[] dataAfter, string appName, string appEndPoint, long currentUserID) {
            return base.Channel.CreateEditApproval(mfbCode, dataType, entityName, objectID, functionID, dataBefore, dataAfter, appName, appEndPoint, currentUserID);
        }
        
        public SOA.Framework.AS.Approval CreateAddApproval(string mfbCode, string dataType, string entityName, long objectID, long functionID, byte[] newData, string appName, string appEndPoint, long currentUserID) {
            return base.Channel.CreateAddApproval(mfbCode, dataType, entityName, objectID, functionID, newData, appName, appEndPoint, currentUserID);
        }
        
        public SOA.Framework.AS.Approval CreateDeleteApproval(string mfbCode, string dataType, string entityName, long objectID, long functionID, byte[] dataToDelete, string appName, string appEndPoint, long currentUserID) {
            return base.Channel.CreateDeleteApproval(mfbCode, dataType, entityName, objectID, functionID, dataToDelete, appName, appEndPoint, currentUserID);
        }
        
        public bool RetrieveByMakerRoleName(string mfbCode, string makerRoleName, long functionID, string appName) {
            return base.Channel.RetrieveByMakerRoleName(mfbCode, makerRoleName, functionID, appName);
        }
        
        public SOA.Framework.AS.TrailItem[] GetApprovalObject(byte[] dataBefore, byte[] dataAfter) {
            return base.Channel.GetApprovalObject(dataBefore, dataAfter);
        }
    }
}
