//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvoPaj.Logic.PrintUtilityServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LicenseData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class LicenseData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rightCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string wrongserviceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rightserviceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicenseFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.errorCodeField, value) != true)) {
                    this.errorCodeField = value;
                    this.RaisePropertyChanged("errorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AdminPassword {
            get {
                return this.AdminPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminPasswordField, value) != true)) {
                    this.AdminPasswordField = value;
                    this.RaisePropertyChanged("AdminPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                if ((object.ReferenceEquals(this.tokenField, value) != true)) {
                    this.tokenField = value;
                    this.RaisePropertyChanged("token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string rightCode {
            get {
                return this.rightCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.rightCodeField, value) != true)) {
                    this.rightCodeField = value;
                    this.RaisePropertyChanged("rightCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string wrongserviceCode {
            get {
                return this.wrongserviceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.wrongserviceCodeField, value) != true)) {
                    this.wrongserviceCodeField = value;
                    this.RaisePropertyChanged("wrongserviceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string rightserviceCode {
            get {
                return this.rightserviceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.rightserviceCodeField, value) != true)) {
                    this.rightserviceCodeField = value;
                    this.RaisePropertyChanged("rightserviceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string LicenseField {
            get {
                return this.LicenseFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.LicenseFieldField, value) != true)) {
                    this.LicenseFieldField = value;
                    this.RaisePropertyChanged("LicenseField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PrintUtilityServiceReference.PrintUtilityServiceSoap")]
    public interface PrintUtilityServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        EvoPaj.Logic.PrintUtilityServiceReference.HelloWorldResponse HelloWorld(EvoPaj.Logic.PrintUtilityServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name token from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateLicenseFromToken", ReplyAction="*")]
        EvoPaj.Logic.PrintUtilityServiceReference.GenerateLicenseFromTokenResponse GenerateLicenseFromToken(EvoPaj.Logic.PrintUtilityServiceReference.GenerateLicenseFromTokenRequest request);
        
        // CODEGEN: Generating message contract since element name errorCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateRightCodeFromErrorCode", ReplyAction="*")]
        EvoPaj.Logic.PrintUtilityServiceReference.GenerateRightCodeFromErrorCodeResponse GenerateRightCodeFromErrorCode(EvoPaj.Logic.PrintUtilityServiceReference.GenerateRightCodeFromErrorCodeRequest request);
        
        // CODEGEN: Generating message contract since element name serviceCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateRightServiceCode", ReplyAction="*")]
        EvoPaj.Logic.PrintUtilityServiceReference.GenerateRightServiceCodeResponse GenerateRightServiceCode(EvoPaj.Logic.PrintUtilityServiceReference.GenerateRightServiceCodeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public EvoPaj.Logic.PrintUtilityServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(EvoPaj.Logic.PrintUtilityServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public EvoPaj.Logic.PrintUtilityServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(EvoPaj.Logic.PrintUtilityServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateLicenseFromTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateLicenseFromToken", Namespace="http://tempuri.org/", Order=0)]
        public EvoPaj.Logic.PrintUtilityServiceReference.GenerateLicenseFromTokenRequestBody Body;
        
        public GenerateLicenseFromTokenRequest() {
        }
        
        public GenerateLicenseFromTokenRequest(EvoPaj.Logic.PrintUtilityServiceReference.GenerateLicenseFromTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateLicenseFromTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string licenseType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string duration;
        
        public GenerateLicenseFromTokenRequestBody() {
        }
        
        public GenerateLicenseFromTokenRequestBody(string token, string licenseType, string duration) {
            this.token = token;
            this.licenseType = licenseType;
            this.duration = duration;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateLicenseFromTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateLicenseFromTokenResponse", Namespace="http://tempuri.org/", Order=0)]
        public EvoPaj.Logic.PrintUtilityServiceReference.GenerateLicenseFromTokenResponseBody Body;
        
        public GenerateLicenseFromTokenResponse() {
        }
        
        public GenerateLicenseFromTokenResponse(EvoPaj.Logic.PrintUtilityServiceReference.GenerateLicenseFromTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateLicenseFromTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EvoPaj.Logic.PrintUtilityServiceReference.LicenseData GenerateLicenseFromTokenResult;
        
        public GenerateLicenseFromTokenResponseBody() {
        }
        
        public GenerateLicenseFromTokenResponseBody(EvoPaj.Logic.PrintUtilityServiceReference.LicenseData GenerateLicenseFromTokenResult) {
            this.GenerateLicenseFromTokenResult = GenerateLicenseFromTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateRightCodeFromErrorCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateRightCodeFromErrorCode", Namespace="http://tempuri.org/", Order=0)]
        public EvoPaj.Logic.PrintUtilityServiceReference.GenerateRightCodeFromErrorCodeRequestBody Body;
        
        public GenerateRightCodeFromErrorCodeRequest() {
        }
        
        public GenerateRightCodeFromErrorCodeRequest(EvoPaj.Logic.PrintUtilityServiceReference.GenerateRightCodeFromErrorCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateRightCodeFromErrorCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string errorCode;
        
        public GenerateRightCodeFromErrorCodeRequestBody() {
        }
        
        public GenerateRightCodeFromErrorCodeRequestBody(string errorCode) {
            this.errorCode = errorCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateRightCodeFromErrorCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateRightCodeFromErrorCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public EvoPaj.Logic.PrintUtilityServiceReference.GenerateRightCodeFromErrorCodeResponseBody Body;
        
        public GenerateRightCodeFromErrorCodeResponse() {
        }
        
        public GenerateRightCodeFromErrorCodeResponse(EvoPaj.Logic.PrintUtilityServiceReference.GenerateRightCodeFromErrorCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateRightCodeFromErrorCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EvoPaj.Logic.PrintUtilityServiceReference.LicenseData GenerateRightCodeFromErrorCodeResult;
        
        public GenerateRightCodeFromErrorCodeResponseBody() {
        }
        
        public GenerateRightCodeFromErrorCodeResponseBody(EvoPaj.Logic.PrintUtilityServiceReference.LicenseData GenerateRightCodeFromErrorCodeResult) {
            this.GenerateRightCodeFromErrorCodeResult = GenerateRightCodeFromErrorCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateRightServiceCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateRightServiceCode", Namespace="http://tempuri.org/", Order=0)]
        public EvoPaj.Logic.PrintUtilityServiceReference.GenerateRightServiceCodeRequestBody Body;
        
        public GenerateRightServiceCodeRequest() {
        }
        
        public GenerateRightServiceCodeRequest(EvoPaj.Logic.PrintUtilityServiceReference.GenerateRightServiceCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateRightServiceCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string serviceCode;
        
        public GenerateRightServiceCodeRequestBody() {
        }
        
        public GenerateRightServiceCodeRequestBody(string serviceCode) {
            this.serviceCode = serviceCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateRightServiceCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateRightServiceCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public EvoPaj.Logic.PrintUtilityServiceReference.GenerateRightServiceCodeResponseBody Body;
        
        public GenerateRightServiceCodeResponse() {
        }
        
        public GenerateRightServiceCodeResponse(EvoPaj.Logic.PrintUtilityServiceReference.GenerateRightServiceCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateRightServiceCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EvoPaj.Logic.PrintUtilityServiceReference.LicenseData GenerateRightServiceCodeResult;
        
        public GenerateRightServiceCodeResponseBody() {
        }
        
        public GenerateRightServiceCodeResponseBody(EvoPaj.Logic.PrintUtilityServiceReference.LicenseData GenerateRightServiceCodeResult) {
            this.GenerateRightServiceCodeResult = GenerateRightServiceCodeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PrintUtilityServiceSoapChannel : EvoPaj.Logic.PrintUtilityServiceReference.PrintUtilityServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrintUtilityServiceSoapClient : System.ServiceModel.ClientBase<EvoPaj.Logic.PrintUtilityServiceReference.PrintUtilityServiceSoap>, EvoPaj.Logic.PrintUtilityServiceReference.PrintUtilityServiceSoap {
        
        public PrintUtilityServiceSoapClient() {
        }
        
        public PrintUtilityServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrintUtilityServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrintUtilityServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrintUtilityServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EvoPaj.Logic.PrintUtilityServiceReference.HelloWorldResponse EvoPaj.Logic.PrintUtilityServiceReference.PrintUtilityServiceSoap.HelloWorld(EvoPaj.Logic.PrintUtilityServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            EvoPaj.Logic.PrintUtilityServiceReference.HelloWorldRequest inValue = new EvoPaj.Logic.PrintUtilityServiceReference.HelloWorldRequest();
            inValue.Body = new EvoPaj.Logic.PrintUtilityServiceReference.HelloWorldRequestBody();
            EvoPaj.Logic.PrintUtilityServiceReference.HelloWorldResponse retVal = ((EvoPaj.Logic.PrintUtilityServiceReference.PrintUtilityServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EvoPaj.Logic.PrintUtilityServiceReference.GenerateLicenseFromTokenResponse EvoPaj.Logic.PrintUtilityServiceReference.PrintUtilityServiceSoap.GenerateLicenseFromToken(EvoPaj.Logic.PrintUtilityServiceReference.GenerateLicenseFromTokenRequest request) {
            return base.Channel.GenerateLicenseFromToken(request);
        }
        
        public EvoPaj.Logic.PrintUtilityServiceReference.LicenseData GenerateLicenseFromToken(string token, string licenseType, string duration) {
            EvoPaj.Logic.PrintUtilityServiceReference.GenerateLicenseFromTokenRequest inValue = new EvoPaj.Logic.PrintUtilityServiceReference.GenerateLicenseFromTokenRequest();
            inValue.Body = new EvoPaj.Logic.PrintUtilityServiceReference.GenerateLicenseFromTokenRequestBody();
            inValue.Body.token = token;
            inValue.Body.licenseType = licenseType;
            inValue.Body.duration = duration;
            EvoPaj.Logic.PrintUtilityServiceReference.GenerateLicenseFromTokenResponse retVal = ((EvoPaj.Logic.PrintUtilityServiceReference.PrintUtilityServiceSoap)(this)).GenerateLicenseFromToken(inValue);
            return retVal.Body.GenerateLicenseFromTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EvoPaj.Logic.PrintUtilityServiceReference.GenerateRightCodeFromErrorCodeResponse EvoPaj.Logic.PrintUtilityServiceReference.PrintUtilityServiceSoap.GenerateRightCodeFromErrorCode(EvoPaj.Logic.PrintUtilityServiceReference.GenerateRightCodeFromErrorCodeRequest request) {
            return base.Channel.GenerateRightCodeFromErrorCode(request);
        }
        
        public EvoPaj.Logic.PrintUtilityServiceReference.LicenseData GenerateRightCodeFromErrorCode(string errorCode) {
            EvoPaj.Logic.PrintUtilityServiceReference.GenerateRightCodeFromErrorCodeRequest inValue = new EvoPaj.Logic.PrintUtilityServiceReference.GenerateRightCodeFromErrorCodeRequest();
            inValue.Body = new EvoPaj.Logic.PrintUtilityServiceReference.GenerateRightCodeFromErrorCodeRequestBody();
            inValue.Body.errorCode = errorCode;
            EvoPaj.Logic.PrintUtilityServiceReference.GenerateRightCodeFromErrorCodeResponse retVal = ((EvoPaj.Logic.PrintUtilityServiceReference.PrintUtilityServiceSoap)(this)).GenerateRightCodeFromErrorCode(inValue);
            return retVal.Body.GenerateRightCodeFromErrorCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EvoPaj.Logic.PrintUtilityServiceReference.GenerateRightServiceCodeResponse EvoPaj.Logic.PrintUtilityServiceReference.PrintUtilityServiceSoap.GenerateRightServiceCode(EvoPaj.Logic.PrintUtilityServiceReference.GenerateRightServiceCodeRequest request) {
            return base.Channel.GenerateRightServiceCode(request);
        }
        
        public EvoPaj.Logic.PrintUtilityServiceReference.LicenseData GenerateRightServiceCode(string serviceCode) {
            EvoPaj.Logic.PrintUtilityServiceReference.GenerateRightServiceCodeRequest inValue = new EvoPaj.Logic.PrintUtilityServiceReference.GenerateRightServiceCodeRequest();
            inValue.Body = new EvoPaj.Logic.PrintUtilityServiceReference.GenerateRightServiceCodeRequestBody();
            inValue.Body.serviceCode = serviceCode;
            EvoPaj.Logic.PrintUtilityServiceReference.GenerateRightServiceCodeResponse retVal = ((EvoPaj.Logic.PrintUtilityServiceReference.PrintUtilityServiceSoap)(this)).GenerateRightServiceCode(inValue);
            return retVal.Body.GenerateRightServiceCodeResult;
        }
    }
}
