//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOA.Framework.US {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseUser", Namespace="http://schemas.datacontract.org/2004/07/AppZonePortal.Core.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOA.Framework.US.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOA.Framework.US.CPCHubUser))]
    public partial class BaseUser : SOA.Framework.US.DataObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BranchIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OtherNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOA.Framework.US.UserStatus StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BranchID {
            get {
                return this.BranchIDField;
            }
            set {
                if ((this.BranchIDField.Equals(value) != true)) {
                    this.BranchIDField = value;
                    this.RaisePropertyChanged("BranchID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OtherNames {
            get {
                return this.OtherNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.OtherNamesField, value) != true)) {
                    this.OtherNamesField = value;
                    this.RaisePropertyChanged("OtherNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOA.Framework.US.UserStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataObject", Namespace="http://schemas.datacontract.org/2004/07/PANE.Framework.DTO")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOA.Framework.US.BaseUser))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOA.Framework.US.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOA.Framework.US.CPCHubUser))]
    public partial class DataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LogObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MFBCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UseAuditTrailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((this.IsDeletedField.Equals(value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LogObject {
            get {
                return this.LogObjectField;
            }
            set {
                if ((this.LogObjectField.Equals(value) != true)) {
                    this.LogObjectField = value;
                    this.RaisePropertyChanged("LogObject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MFBCode {
            get {
                return this.MFBCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MFBCodeField, value) != true)) {
                    this.MFBCodeField = value;
                    this.RaisePropertyChanged("MFBCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UseAuditTrail {
            get {
                return this.UseAuditTrailField;
            }
            set {
                if ((this.UseAuditTrailField.Equals(value) != true)) {
                    this.UseAuditTrailField = value;
                    this.RaisePropertyChanged("UseAuditTrail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/AppZonePortal.Core.Data")]
    [System.SerializableAttribute()]
    public partial class User : SOA.Framework.US.BaseUser {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CPCHubUser", Namespace="http://schemas.datacontract.org/2004/07/AppZonePortal.Core.Data")]
    [System.SerializableAttribute()]
    public partial class CPCHubUser : SOA.Framework.US.BaseUser {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CPCHubIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPCHubNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CPCHubID {
            get {
                return this.CPCHubIDField;
            }
            set {
                if ((this.CPCHubIDField.Equals(value) != true)) {
                    this.CPCHubIDField = value;
                    this.RaisePropertyChanged("CPCHubID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CPCHubName {
            get {
                return this.CPCHubNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CPCHubNameField, value) != true)) {
                    this.CPCHubNameField = value;
                    this.RaisePropertyChanged("CPCHubName");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserStatus", Namespace="http://schemas.datacontract.org/2004/07/PANE.Framework.Managed.Functions.DTO")]
    public enum UserStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InActive = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="US.IUtilityService")]
    public interface IUtilityService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilityService/GetApplicationUrl", ReplyAction="http://tempuri.org/IUtilityService/GetApplicationUrlResponse")]
        string GetApplicationUrl();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilityService/RetrieveUsersByUserRolesAndApprovingUsers", ReplyAction="http://tempuri.org/IUtilityService/RetrieveUsersByUserRolesAndApprovingUsersRespo" +
            "nse")]
        SOA.Framework.US.BaseUser[] RetrieveUsersByUserRolesAndApprovingUsers(string mfbCode, long[] approvingRoleIDs, long userIDToIgnore);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilityService/SendEmail", ReplyAction="http://tempuri.org/IUtilityService/SendEmailResponse")]
        bool SendEmail(string title, string toAddress, string body);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUtilityServiceChannel : SOA.Framework.US.IUtilityService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UtilityServiceClient : System.ServiceModel.ClientBase<SOA.Framework.US.IUtilityService>, SOA.Framework.US.IUtilityService {
        
        public UtilityServiceClient() {
        }
        
        public UtilityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UtilityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetApplicationUrl() {
            return base.Channel.GetApplicationUrl();
        }
        
        public SOA.Framework.US.BaseUser[] RetrieveUsersByUserRolesAndApprovingUsers(string mfbCode, long[] approvingRoleIDs, long userIDToIgnore) {
            return base.Channel.RetrieveUsersByUserRolesAndApprovingUsers(mfbCode, approvingRoleIDs, userIDToIgnore);
        }
        
        public bool SendEmail(string title, string toAddress, string body) {
            return base.Channel.SendEmail(title, toAddress, body);
        }
    }
}
