//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOA.Framework.FS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserCategory", Namespace="http://schemas.datacontract.org/2004/07/PANE.Framework.Managed.Functions.DTO")]
    public enum UserCategory : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServiceProvider = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mfb = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CorrespondentBank = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Customer = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FunctionItem", Namespace="http://schemas.datacontract.org/2004/07/SOA.Framework.FunctionHelper")]
    [System.SerializableAttribute()]
    public partial class FunctionItem : SOA.Framework.FS.DataObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOA.Framework.FS.ApprovalConfig ApprovalConfigurationUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DependencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasSubRolesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> InstitutionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsApprovableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDefaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOA.Framework.FS.FunctionItem ParentFunctionItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOA.Framework.FS.UserRole SubUserRoleUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SOA.Framework.FS.ApprovalConfig> TheApprovalConfigurationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOA.Framework.FS.UserCategory UserCategoryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOA.Framework.FS.ApprovalConfig ApprovalConfigurationUpdate {
            get {
                return this.ApprovalConfigurationUpdateField;
            }
            set {
                if ((object.ReferenceEquals(this.ApprovalConfigurationUpdateField, value) != true)) {
                    this.ApprovalConfigurationUpdateField = value;
                    this.RaisePropertyChanged("ApprovalConfigurationUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Dependency {
            get {
                return this.DependencyField;
            }
            set {
                if ((this.DependencyField.Equals(value) != true)) {
                    this.DependencyField = value;
                    this.RaisePropertyChanged("Dependency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasSubRoles {
            get {
                return this.HasSubRolesField;
            }
            set {
                if ((this.HasSubRolesField.Equals(value) != true)) {
                    this.HasSubRolesField = value;
                    this.RaisePropertyChanged("HasSubRoles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> InstitutionID {
            get {
                return this.InstitutionIDField;
            }
            set {
                if ((this.InstitutionIDField.Equals(value) != true)) {
                    this.InstitutionIDField = value;
                    this.RaisePropertyChanged("InstitutionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsApprovable {
            get {
                return this.IsApprovableField;
            }
            set {
                if ((this.IsApprovableField.Equals(value) != true)) {
                    this.IsApprovableField = value;
                    this.RaisePropertyChanged("IsApprovable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDefault {
            get {
                return this.IsDefaultField;
            }
            set {
                if ((this.IsDefaultField.Equals(value) != true)) {
                    this.IsDefaultField = value;
                    this.RaisePropertyChanged("IsDefault");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOA.Framework.FS.FunctionItem ParentFunctionItem {
            get {
                return this.ParentFunctionItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentFunctionItemField, value) != true)) {
                    this.ParentFunctionItemField = value;
                    this.RaisePropertyChanged("ParentFunctionItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOA.Framework.FS.UserRole SubUserRoleUpdate {
            get {
                return this.SubUserRoleUpdateField;
            }
            set {
                if ((object.ReferenceEquals(this.SubUserRoleUpdateField, value) != true)) {
                    this.SubUserRoleUpdateField = value;
                    this.RaisePropertyChanged("SubUserRoleUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SOA.Framework.FS.ApprovalConfig> TheApprovalConfigurations {
            get {
                return this.TheApprovalConfigurationsField;
            }
            set {
                if ((object.ReferenceEquals(this.TheApprovalConfigurationsField, value) != true)) {
                    this.TheApprovalConfigurationsField = value;
                    this.RaisePropertyChanged("TheApprovalConfigurations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOA.Framework.FS.UserCategory UserCategory {
            get {
                return this.UserCategoryField;
            }
            set {
                if ((this.UserCategoryField.Equals(value) != true)) {
                    this.UserCategoryField = value;
                    this.RaisePropertyChanged("UserCategory");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataObject", Namespace="http://schemas.datacontract.org/2004/07/PANE.Framework.DTO")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOA.Framework.FS.UserRole))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOA.Framework.FS.Function))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOA.Framework.FS.ApprovalConfiguration))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOA.Framework.FS.ApprovalConfig))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOA.Framework.FS.UserRoleFunctionItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOA.Framework.FS.FunctionItem))]
    public partial class DataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LogObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MFBCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UseAuditTrailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((this.IsDeletedField.Equals(value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LogObject {
            get {
                return this.LogObjectField;
            }
            set {
                if ((this.LogObjectField.Equals(value) != true)) {
                    this.LogObjectField = value;
                    this.RaisePropertyChanged("LogObject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MFBCode {
            get {
                return this.MFBCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MFBCodeField, value) != true)) {
                    this.MFBCodeField = value;
                    this.RaisePropertyChanged("MFBCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UseAuditTrail {
            get {
                return this.UseAuditTrailField;
            }
            set {
                if ((this.UseAuditTrailField.Equals(value) != true)) {
                    this.UseAuditTrailField = value;
                    this.RaisePropertyChanged("UseAuditTrail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRole", Namespace="http://schemas.datacontract.org/2004/07/PANE.Framework.Functions.DTO")]
    [System.SerializableAttribute()]
    public partial class UserRole : SOA.Framework.FS.DataObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOA.Framework.FS.UserRoleScope ScopeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOA.Framework.FS.UserCategory UserCategoryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOA.Framework.FS.UserRoleScope Scope {
            get {
                return this.ScopeField;
            }
            set {
                if ((this.ScopeField.Equals(value) != true)) {
                    this.ScopeField = value;
                    this.RaisePropertyChanged("Scope");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOA.Framework.FS.UserCategory UserCategory {
            get {
                return this.UserCategoryField;
            }
            set {
                if ((this.UserCategoryField.Equals(value) != true)) {
                    this.UserCategoryField = value;
                    this.RaisePropertyChanged("UserCategory");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Function", Namespace="http://schemas.datacontract.org/2004/07/PANE.Framework.Functions.DTO")]
    [System.SerializableAttribute()]
    public partial class Function : SOA.Framework.FS.DataObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ApplicationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOA.Framework.FS.ApprovalConfiguration ApprovalConfigurationUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasSubRolesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> InstitutionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsApprovableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDefaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOA.Framework.FS.Function ParentFunctionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOA.Framework.FS.UserRole SubUserRoleUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SOA.Framework.FS.ApprovalConfiguration> TheApprovalConfigurationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOA.Framework.FS.UserCategory UserCategoryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ApplicationID {
            get {
                return this.ApplicationIDField;
            }
            set {
                if ((this.ApplicationIDField.Equals(value) != true)) {
                    this.ApplicationIDField = value;
                    this.RaisePropertyChanged("ApplicationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOA.Framework.FS.ApprovalConfiguration ApprovalConfigurationUpdate {
            get {
                return this.ApprovalConfigurationUpdateField;
            }
            set {
                if ((object.ReferenceEquals(this.ApprovalConfigurationUpdateField, value) != true)) {
                    this.ApprovalConfigurationUpdateField = value;
                    this.RaisePropertyChanged("ApprovalConfigurationUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasSubRoles {
            get {
                return this.HasSubRolesField;
            }
            set {
                if ((this.HasSubRolesField.Equals(value) != true)) {
                    this.HasSubRolesField = value;
                    this.RaisePropertyChanged("HasSubRoles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> InstitutionID {
            get {
                return this.InstitutionIDField;
            }
            set {
                if ((this.InstitutionIDField.Equals(value) != true)) {
                    this.InstitutionIDField = value;
                    this.RaisePropertyChanged("InstitutionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsApprovable {
            get {
                return this.IsApprovableField;
            }
            set {
                if ((this.IsApprovableField.Equals(value) != true)) {
                    this.IsApprovableField = value;
                    this.RaisePropertyChanged("IsApprovable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDefault {
            get {
                return this.IsDefaultField;
            }
            set {
                if ((this.IsDefaultField.Equals(value) != true)) {
                    this.IsDefaultField = value;
                    this.RaisePropertyChanged("IsDefault");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOA.Framework.FS.Function ParentFunction {
            get {
                return this.ParentFunctionField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentFunctionField, value) != true)) {
                    this.ParentFunctionField = value;
                    this.RaisePropertyChanged("ParentFunction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOA.Framework.FS.UserRole SubUserRoleUpdate {
            get {
                return this.SubUserRoleUpdateField;
            }
            set {
                if ((object.ReferenceEquals(this.SubUserRoleUpdateField, value) != true)) {
                    this.SubUserRoleUpdateField = value;
                    this.RaisePropertyChanged("SubUserRoleUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SOA.Framework.FS.ApprovalConfiguration> TheApprovalConfigurations {
            get {
                return this.TheApprovalConfigurationsField;
            }
            set {
                if ((object.ReferenceEquals(this.TheApprovalConfigurationsField, value) != true)) {
                    this.TheApprovalConfigurationsField = value;
                    this.RaisePropertyChanged("TheApprovalConfigurations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOA.Framework.FS.UserCategory UserCategory {
            get {
                return this.UserCategoryField;
            }
            set {
                if ((this.UserCategoryField.Equals(value) != true)) {
                    this.UserCategoryField = value;
                    this.RaisePropertyChanged("UserCategory");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApprovalConfiguration", Namespace="http://schemas.datacontract.org/2004/07/PANE.Framework.Approval.DTO")]
    [System.SerializableAttribute()]
    public partial class ApprovalConfiguration : SOA.Framework.FS.DataObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOA.Framework.FS.UserRole ApprovingRoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ApprovingRoleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsApprovableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakeRoleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MakerRoleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationName {
            get {
                return this.ApplicationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationNameField, value) != true)) {
                    this.ApplicationNameField = value;
                    this.RaisePropertyChanged("ApplicationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOA.Framework.FS.UserRole ApprovingRole {
            get {
                return this.ApprovingRoleField;
            }
            set {
                if ((object.ReferenceEquals(this.ApprovingRoleField, value) != true)) {
                    this.ApprovingRoleField = value;
                    this.RaisePropertyChanged("ApprovingRole");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ApprovingRoleID {
            get {
                return this.ApprovingRoleIDField;
            }
            set {
                if ((this.ApprovingRoleIDField.Equals(value) != true)) {
                    this.ApprovingRoleIDField = value;
                    this.RaisePropertyChanged("ApprovingRoleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsApprovable {
            get {
                return this.IsApprovableField;
            }
            set {
                if ((this.IsApprovableField.Equals(value) != true)) {
                    this.IsApprovableField = value;
                    this.RaisePropertyChanged("IsApprovable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MakeRoleName {
            get {
                return this.MakeRoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MakeRoleNameField, value) != true)) {
                    this.MakeRoleNameField = value;
                    this.RaisePropertyChanged("MakeRoleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MakerRole {
            get {
                return this.MakerRoleField;
            }
            set {
                if ((this.MakerRoleField.Equals(value) != true)) {
                    this.MakerRoleField = value;
                    this.RaisePropertyChanged("MakerRole");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApprovalConfig", Namespace="http://schemas.datacontract.org/2004/07/SOA.Framework.ApprovalConfigHelper")]
    [System.SerializableAttribute()]
    public partial class ApprovalConfig : SOA.Framework.FS.DataObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ApprovingRoleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsApprovableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakeRoleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MakerRoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SubUserRoleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ApprovingRoleID {
            get {
                return this.ApprovingRoleIDField;
            }
            set {
                if ((this.ApprovingRoleIDField.Equals(value) != true)) {
                    this.ApprovingRoleIDField = value;
                    this.RaisePropertyChanged("ApprovingRoleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsApprovable {
            get {
                return this.IsApprovableField;
            }
            set {
                if ((this.IsApprovableField.Equals(value) != true)) {
                    this.IsApprovableField = value;
                    this.RaisePropertyChanged("IsApprovable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MakeRoleName {
            get {
                return this.MakeRoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MakeRoleNameField, value) != true)) {
                    this.MakeRoleNameField = value;
                    this.RaisePropertyChanged("MakeRoleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MakerRole {
            get {
                return this.MakerRoleField;
            }
            set {
                if ((this.MakerRoleField.Equals(value) != true)) {
                    this.MakerRoleField = value;
                    this.RaisePropertyChanged("MakerRole");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SubUserRole {
            get {
                return this.SubUserRoleField;
            }
            set {
                if ((this.SubUserRoleField.Equals(value) != true)) {
                    this.SubUserRoleField = value;
                    this.RaisePropertyChanged("SubUserRole");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRoleFunctionItem", Namespace="http://schemas.datacontract.org/2004/07/SOA.Framework.FunctionHelper")]
    [System.SerializableAttribute()]
    public partial class UserRoleFunctionItem : SOA.Framework.FS.DataObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TheFunctionItemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TheUserRoleIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TheFunctionItemID {
            get {
                return this.TheFunctionItemIDField;
            }
            set {
                if ((this.TheFunctionItemIDField.Equals(value) != true)) {
                    this.TheFunctionItemIDField = value;
                    this.RaisePropertyChanged("TheFunctionItemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TheUserRoleID {
            get {
                return this.TheUserRoleIDField;
            }
            set {
                if ((this.TheUserRoleIDField.Equals(value) != true)) {
                    this.TheUserRoleIDField = value;
                    this.RaisePropertyChanged("TheUserRoleID");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRoleScope", Namespace="http://schemas.datacontract.org/2004/07/PANE.Framework.Managed.Functions.DTO")]
    public enum UserRoleScope : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Branch = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Region = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Global = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="FS.FunctionService")]
    public interface FunctionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:FunctionService/GetFunctionsForApprovalConfiguration", ReplyAction="urn:FunctionService/GetFunctionsForApprovalConfigurationResponse")]
        System.Collections.Generic.List<SOA.Framework.FS.FunctionItem> GetFunctionsForApprovalConfiguration(SOA.Framework.FS.UserCategory userCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:FunctionService/RetrieveAll", ReplyAction="urn:FunctionService/RetrieveAllResponse")]
        System.Collections.Generic.List<SOA.Framework.FS.FunctionItem> RetrieveAll(SOA.Framework.FS.UserCategory userCategory);
        
        // CODEGEN: Generating message contract since the wrapper name (GetFunctionsForApprovalConfiguration_x0020_Per_x0020_Institution) of message GetFunctionsForApprovalConfiguration_x0020_Per_x0020_InstitutionRequest does not match the default value (GetFunctionsForApprovalConfigurationPerInstitution)
        [System.ServiceModel.OperationContractAttribute(Action="urn:FunctionService/GetFunctionsForApprovalConfiguration Per Institution", ReplyAction="urn:FunctionService/GetFunctionsForApprovalConfiguration Per InstitutionResponse")]
        SOA.Framework.FS.GetFunctionsForApprovalConfigurationPerInstitutionResponse GetFunctionsForApprovalConfigurationPerInstitution(SOA.Framework.FS.GetFunctionsForApprovalConfigurationPerInstitutionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (RetrieveAll_x0020_Per_x0020_Institution) of message RetrieveAll_x0020_Per_x0020_InstitutionRequest does not match the default value (RetrieveAllPerInstitution)
        [System.ServiceModel.OperationContractAttribute(Action="urn:FunctionService/RetrieveAll Per Institution", ReplyAction="urn:FunctionService/RetrieveAll Per InstitutionResponse")]
        SOA.Framework.FS.RetrieveAllPerInstitutionResponse RetrieveAllPerInstitution(SOA.Framework.FS.RetrieveAllPerInstitutionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:FunctionService/SaveThUserRoleFunctionItems", ReplyAction="urn:FunctionService/SaveThUserRoleFunctionItemsResponse")]
        bool SaveThUserRoleFunctionItems(string mfbCode, System.Collections.Generic.List<SOA.Framework.FS.UserRoleFunctionItem> userRoleFunctionItems);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:FunctionService/UpdateThUserRoleFunctionItems", ReplyAction="urn:FunctionService/UpdateThUserRoleFunctionItemsResponse")]
        bool UpdateThUserRoleFunctionItems(string mfbCode, System.Collections.Generic.List<SOA.Framework.FS.UserRoleFunctionItem> userRoleFunctionItems, long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:FunctionService/ConvertFunction", ReplyAction="urn:FunctionService/ConvertFunctionResponse")]
        SOA.Framework.FS.FunctionItem ConvertFunction(SOA.Framework.FS.Function function);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:FunctionService/GetFunctionByID", ReplyAction="urn:FunctionService/GetFunctionByIDResponse")]
        SOA.Framework.FS.FunctionItem GetFunctionByID(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:FunctionService/GetFunctionByRoleName", ReplyAction="urn:FunctionService/GetFunctionByRoleNameResponse")]
        SOA.Framework.FS.FunctionItem GetFunctionByRoleName(string rolename, SOA.Framework.FS.UserCategory userCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:FunctionService/GetFunctionsForUserRole", ReplyAction="urn:FunctionService/GetFunctionsForUserRoleResponse")]
        System.Collections.Generic.List<SOA.Framework.FS.FunctionItem> GetFunctionsForUserRole(string mfbCode, long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:FunctionService/GetDependencyFunctionsForUserRole", ReplyAction="urn:FunctionService/GetDependencyFunctionsForUserRoleResponse")]
        System.Collections.Generic.List<SOA.Framework.FS.FunctionItem> GetDependencyFunctionsForUserRole(string mfbCode, long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:FunctionService/RetrieveFunctionItemsForUserRoleID", ReplyAction="urn:FunctionService/RetrieveFunctionItemsForUserRoleIDResponse")]
        System.Collections.Generic.List<SOA.Framework.FS.FunctionItem> RetrieveFunctionItemsForUserRoleID(string mfbCode, long userRoleID);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFunctionsForApprovalConfiguration Per Institution", WrapperNamespace="", IsWrapped=true)]
    public partial class GetFunctionsForApprovalConfigurationPerInstitutionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public System.Nullable<long> instiutionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public SOA.Framework.FS.UserCategory userCategory;
        
        public GetFunctionsForApprovalConfigurationPerInstitutionRequest() {
        }
        
        public GetFunctionsForApprovalConfigurationPerInstitutionRequest(System.Nullable<long> instiutionID, SOA.Framework.FS.UserCategory userCategory) {
            this.instiutionID = instiutionID;
            this.userCategory = userCategory;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFunctionsForApprovalConfiguration Per InstitutionResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class GetFunctionsForApprovalConfigurationPerInstitutionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFunctionsForApprovalConfiguration_x0020_Per_x0020_InstitutionResult", Namespace="", Order=0)]
        public System.Collections.Generic.List<SOA.Framework.FS.FunctionItem> GetFunctionsForApprovalConfigurationPerInstitutionResult;
        
        public GetFunctionsForApprovalConfigurationPerInstitutionResponse() {
        }
        
        public GetFunctionsForApprovalConfigurationPerInstitutionResponse(System.Collections.Generic.List<SOA.Framework.FS.FunctionItem> GetFunctionsForApprovalConfigurationPerInstitutionResult) {
            this.GetFunctionsForApprovalConfigurationPerInstitutionResult = GetFunctionsForApprovalConfigurationPerInstitutionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RetrieveAll Per Institution", WrapperNamespace="", IsWrapped=true)]
    public partial class RetrieveAllPerInstitutionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public System.Nullable<long> instiutionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public SOA.Framework.FS.UserCategory userCategory;
        
        public RetrieveAllPerInstitutionRequest() {
        }
        
        public RetrieveAllPerInstitutionRequest(System.Nullable<long> instiutionID, SOA.Framework.FS.UserCategory userCategory) {
            this.instiutionID = instiutionID;
            this.userCategory = userCategory;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RetrieveAll Per InstitutionResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class RetrieveAllPerInstitutionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveAll_x0020_Per_x0020_InstitutionResult", Namespace="", Order=0)]
        public System.Collections.Generic.List<SOA.Framework.FS.FunctionItem> RetrieveAllPerInstitutionResult;
        
        public RetrieveAllPerInstitutionResponse() {
        }
        
        public RetrieveAllPerInstitutionResponse(System.Collections.Generic.List<SOA.Framework.FS.FunctionItem> RetrieveAllPerInstitutionResult) {
            this.RetrieveAllPerInstitutionResult = RetrieveAllPerInstitutionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FunctionServiceChannel : SOA.Framework.FS.FunctionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FunctionServiceClient : System.ServiceModel.ClientBase<SOA.Framework.FS.FunctionService>, SOA.Framework.FS.FunctionService {
        
        public FunctionServiceClient() {
        }
        
        public FunctionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FunctionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FunctionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FunctionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<SOA.Framework.FS.FunctionItem> GetFunctionsForApprovalConfiguration(SOA.Framework.FS.UserCategory userCategory) {
            return base.Channel.GetFunctionsForApprovalConfiguration(userCategory);
        }
        
        public System.Collections.Generic.List<SOA.Framework.FS.FunctionItem> RetrieveAll(SOA.Framework.FS.UserCategory userCategory) {
            return base.Channel.RetrieveAll(userCategory);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOA.Framework.FS.GetFunctionsForApprovalConfigurationPerInstitutionResponse SOA.Framework.FS.FunctionService.GetFunctionsForApprovalConfigurationPerInstitution(SOA.Framework.FS.GetFunctionsForApprovalConfigurationPerInstitutionRequest request) {
            return base.Channel.GetFunctionsForApprovalConfigurationPerInstitution(request);
        }
        
        public System.Collections.Generic.List<SOA.Framework.FS.FunctionItem> GetFunctionsForApprovalConfigurationPerInstitution(System.Nullable<long> instiutionID, SOA.Framework.FS.UserCategory userCategory) {
            SOA.Framework.FS.GetFunctionsForApprovalConfigurationPerInstitutionRequest inValue = new SOA.Framework.FS.GetFunctionsForApprovalConfigurationPerInstitutionRequest();
            inValue.instiutionID = instiutionID;
            inValue.userCategory = userCategory;
            SOA.Framework.FS.GetFunctionsForApprovalConfigurationPerInstitutionResponse retVal = ((SOA.Framework.FS.FunctionService)(this)).GetFunctionsForApprovalConfigurationPerInstitution(inValue);
            return retVal.GetFunctionsForApprovalConfigurationPerInstitutionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOA.Framework.FS.RetrieveAllPerInstitutionResponse SOA.Framework.FS.FunctionService.RetrieveAllPerInstitution(SOA.Framework.FS.RetrieveAllPerInstitutionRequest request) {
            return base.Channel.RetrieveAllPerInstitution(request);
        }
        
        public System.Collections.Generic.List<SOA.Framework.FS.FunctionItem> RetrieveAllPerInstitution(System.Nullable<long> instiutionID, SOA.Framework.FS.UserCategory userCategory) {
            SOA.Framework.FS.RetrieveAllPerInstitutionRequest inValue = new SOA.Framework.FS.RetrieveAllPerInstitutionRequest();
            inValue.instiutionID = instiutionID;
            inValue.userCategory = userCategory;
            SOA.Framework.FS.RetrieveAllPerInstitutionResponse retVal = ((SOA.Framework.FS.FunctionService)(this)).RetrieveAllPerInstitution(inValue);
            return retVal.RetrieveAllPerInstitutionResult;
        }
        
        public bool SaveThUserRoleFunctionItems(string mfbCode, System.Collections.Generic.List<SOA.Framework.FS.UserRoleFunctionItem> userRoleFunctionItems) {
            return base.Channel.SaveThUserRoleFunctionItems(mfbCode, userRoleFunctionItems);
        }
        
        public bool UpdateThUserRoleFunctionItems(string mfbCode, System.Collections.Generic.List<SOA.Framework.FS.UserRoleFunctionItem> userRoleFunctionItems, long id) {
            return base.Channel.UpdateThUserRoleFunctionItems(mfbCode, userRoleFunctionItems, id);
        }
        
        public SOA.Framework.FS.FunctionItem ConvertFunction(SOA.Framework.FS.Function function) {
            return base.Channel.ConvertFunction(function);
        }
        
        public SOA.Framework.FS.FunctionItem GetFunctionByID(long id) {
            return base.Channel.GetFunctionByID(id);
        }
        
        public SOA.Framework.FS.FunctionItem GetFunctionByRoleName(string rolename, SOA.Framework.FS.UserCategory userCategory) {
            return base.Channel.GetFunctionByRoleName(rolename, userCategory);
        }
        
        public System.Collections.Generic.List<SOA.Framework.FS.FunctionItem> GetFunctionsForUserRole(string mfbCode, long id) {
            return base.Channel.GetFunctionsForUserRole(mfbCode, id);
        }
        
        public System.Collections.Generic.List<SOA.Framework.FS.FunctionItem> GetDependencyFunctionsForUserRole(string mfbCode, long id) {
            return base.Channel.GetDependencyFunctionsForUserRole(mfbCode, id);
        }
        
        public System.Collections.Generic.List<SOA.Framework.FS.FunctionItem> RetrieveFunctionItemsForUserRoleID(string mfbCode, long userRoleID) {
            return base.Channel.RetrieveFunctionItemsForUserRoleID(mfbCode, userRoleID);
        }
    }
}
