//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOA.Framework.MS
{
    using System.Runtime.Serialization;
    using System;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MembershipUserItem", Namespace = "http://schemas.datacontract.org/2004/07/SOA.Framework.MembershipHelper")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOA.Framework.MS.MembershipBranchItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PANE.Framework.Managed.Functions.DTO.Status))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PANE.Framework.Managed.Functions.DTO.UserRole))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PANE.Framework.Managed.Functions.DTO.UserRoleScope))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PANE.Framework.Managed.Functions.DTO.UserStatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PANE.Framework.Managed.DTO.DataObject))]
    public partial class MembershipUserItem : object, System.Runtime.Serialization.IExtensibleDataObject, PANE.Framework.Managed.Functions.DTO.IUser, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BranchIDField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DoesntNeedAuditField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FailedPasswordAttemptCountField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsApprovedField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLockedOutField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOnlineField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object KeyField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastLoginDateField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MFBCodeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOA.Framework.MS.MembershipBranchItem MembershipBranchItemField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PANE.Framework.Managed.Functions.DTO.UserRole RoleField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PANE.Framework.Managed.Functions.DTO.UserStatus StatusField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PANE.Framework.Managed.Functions.DTO.IBranch BranchField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuperUserField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BranchID
        {
            get
            {
                return this.BranchIDField;
            }
            set
            {
                if ((this.BranchIDField.Equals(value) != true))
                {
                    this.BranchIDField = value;
                    this.RaisePropertyChanged("BranchID");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public PANE.Framework.Managed.Functions.DTO.IBranch Branch
        {
            get
            {
                return this.MembershipBranchItemField;
            }
            set
            {
                if ((object.ReferenceEquals(this.MembershipBranchItemField, value) != true))
                {
                    this.MembershipBranchItemField = (MembershipBranchItem)value;
                    this.RaisePropertyChanged("MembershipBranchItem");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuperUser
        {
            get
            {
                return this.IsSuperUserField;
            }
            set
            {
                if ((this.IsSuperUserField.Equals(value) != true))
                {
                    this.IsSuperUserField = value;
                    this.RaisePropertyChanged("IsSuperUser");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this.CommentField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CommentField, value) != true))
                {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate
        {
            get
            {
                return this.CreationDateField;
            }
            set
            {
                if ((this.CreationDateField.Equals(value) != true))
                {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DoesntNeedAudit
        {
            get
            {
                return this.DoesntNeedAuditField;
            }
            set
            {
                if ((this.DoesntNeedAuditField.Equals(value) != true))
                {
                    this.DoesntNeedAuditField = value;
                    this.RaisePropertyChanged("DoesntNeedAudit");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                if ((object.ReferenceEquals(this.EmailField, value) != true))
                {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FailedPasswordAttemptCount
        {
            get
            {
                return this.FailedPasswordAttemptCountField;
            }
            set
            {
                if ((this.FailedPasswordAttemptCountField.Equals(value) != true))
                {
                    this.FailedPasswordAttemptCountField = value;
                    this.RaisePropertyChanged("FailedPasswordAttemptCount");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                if ((this.IDField.Equals(value) != true))
                {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsApproved
        {
            get
            {
                return this.IsApprovedField;
            }
            set
            {
                if ((this.IsApprovedField.Equals(value) != true))
                {
                    this.IsApprovedField = value;
                    this.RaisePropertyChanged("IsApproved");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLockedOut
        {
            get
            {
                return this.IsLockedOutField;
            }
            set
            {
                if ((this.IsLockedOutField.Equals(value) != true))
                {
                    this.IsLockedOutField = value;
                    this.RaisePropertyChanged("IsLockedOut");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOnline
        {
            get
            {
                return this.IsOnlineField;
            }
            set
            {
                if ((this.IsOnlineField.Equals(value) != true))
                {
                    this.IsOnlineField = value;
                    this.RaisePropertyChanged("IsOnline");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                if ((object.ReferenceEquals(this.KeyField, value) != true))
                {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastLoginDate
        {
            get
            {
                return this.LastLoginDateField;
            }
            set
            {
                if ((this.LastLoginDateField.Equals(value) != true))
                {
                    this.LastLoginDateField = value;
                    this.RaisePropertyChanged("LastLoginDate");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MFBCode
        {
            get
            {
                if (!String.IsNullOrEmpty(this.UserNameField))
                {
                    string[] userInfo = this.UserNameField.Split(':');
                    if (userInfo.Length > 1)
                    {
                        return userInfo[1];
                    }
                    return null;
                }
                return null;
            }
            set
            {
               
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOA.Framework.MS.MembershipBranchItem MembershipBranchItem
        {
            get
            {
                return this.MembershipBranchItemField;
            }
            set
            {
                if ((object.ReferenceEquals(this.MembershipBranchItemField, value) != true))
                {
                    this.MembershipBranchItemField = value;
                    this.RaisePropertyChanged("MembershipBranchItem");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PasswordField, value) != true))
                {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public PANE.Framework.Managed.Functions.DTO.UserRole Role
        {
            get
            {
                return this.RoleField;
            }
            set
            {
                if ((object.ReferenceEquals(this.RoleField, value) != true))
                {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public PANE.Framework.Managed.Functions.DTO.UserStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                if ((this.StatusField.Equals(value) != true))
                {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.UserNameField, value) != true))
                {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                if ((object.ReferenceEquals(this.UserIDField, value) != true))
                {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MembershipBranchItem", Namespace = "http://schemas.datacontract.org/2004/07/SOA.Framework.MembershipHelper")]
    [System.SerializableAttribute()]
    public partial class MembershipBranchItem : object, System.Runtime.Serialization.IExtensibleDataObject, PANE.Framework.Managed.Functions.DTO.IBranch, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RegionIDField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MFBCodeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;

        //[System.Runtime.Serialization.OptionalFieldAttribute()]
        //private string GefuFilePathField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PANE.Framework.Managed.Functions.DTO.Status StatusField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AddressField, value) != true))
                {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                if ((this.CodeField.Equals(value) != true))
                {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                if ((this.IDField.Equals(value) != true))
                {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RegionID
        {
            get
            {
                return this.RegionIDField;
            }
            set
            {
                if ((this.RegionIDField.Equals(value) != true))
                {
                    this.RegionIDField = value;
                    this.RaisePropertyChanged("RegionID");
                }
            }
        }

        //[System.Runtime.Serialization.DataMemberAttribute()]
        //public string GefuFilePath
        //{
        //    get
        //    {
        //        return this.GefuFilePathField;
        //    }
        //    set
        //    {
        //        if ((this.GefuFilePathField.Equals(value) != true))
        //        {
        //            this.GefuFilePathField = value;
        //            this.RaisePropertyChanged("GefuFilePath");
        //        }
        //    }
        //}


        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MFBCode
        {
            get
            {
                return this.MFBCodeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.MFBCodeField, value) != true))
                {
                    this.MFBCodeField = value;
                    this.RaisePropertyChanged("MFBCode");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NameField, value) != true))
                {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public PANE.Framework.Managed.Functions.DTO.Status Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                if ((this.StatusField.Equals(value) != true))
                {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "", ConfigurationName = "MS.MembershipService")]
    public interface MembershipService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "urn:MembershipService/GetUser", ReplyAction = "urn:MembershipService/GetUserResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOA.Framework.MS.MembershipUserItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOA.Framework.MS.MembershipBranchItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PANE.Framework.Managed.Functions.DTO.Status))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PANE.Framework.Managed.Functions.DTO.UserRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PANE.Framework.Managed.Functions.DTO.UserRoleScope))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PANE.Framework.Managed.Functions.DTO.UserStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PANE.Framework.Managed.DTO.DataObject))]
        SOA.Framework.MS.MembershipUserItem GetUser(string username, bool userIsOnline);

        [System.ServiceModel.OperationContractAttribute(Action = "urn:MembershipService/GetUserByKey", ReplyAction = "urn:MembershipService/GetUserByKeyResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOA.Framework.MS.MembershipUserItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOA.Framework.MS.MembershipBranchItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PANE.Framework.Managed.Functions.DTO.Status))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PANE.Framework.Managed.Functions.DTO.UserRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PANE.Framework.Managed.Functions.DTO.UserRoleScope))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PANE.Framework.Managed.Functions.DTO.UserStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PANE.Framework.Managed.DTO.DataObject))]
        SOA.Framework.MS.MembershipUserItem GetUserByKey(object providerUserKey, bool userIsOnline);

        [System.ServiceModel.OperationContractAttribute(Action = "urn:MembershipService/ValidateUser", ReplyAction = "urn:MembershipService/ValidateUserResponse")]
        bool ValidateUser(string username, string password);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface MembershipServiceChannel : SOA.Framework.MS.MembershipService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class MembershipServiceClient : System.ServiceModel.ClientBase<SOA.Framework.MS.MembershipService>, SOA.Framework.MS.MembershipService
    {

        public MembershipServiceClient()
        {
        }

        public MembershipServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public MembershipServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public MembershipServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public MembershipServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public SOA.Framework.MS.MembershipUserItem GetUser(string username, bool userIsOnline)
        {
            return base.Channel.GetUser(username, userIsOnline);
        }

        public SOA.Framework.MS.MembershipUserItem GetUserByKey(object providerUserKey, bool userIsOnline)
        {
            return base.Channel.GetUserByKey(providerUserKey, userIsOnline);
        }

        public bool ValidateUser(string username, string password)
        {
            return base.Channel.ValidateUser(username, password);
        }
    }
}
