//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOA.Framework.RA {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecentActivity", Namespace="http://schemas.datacontract.org/2004/07/ManagedServices.Data.Utility")]
    [System.SerializableAttribute()]
    public partial class RecentActivity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ActivityDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ActivityIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ActivityDate {
            get {
                return this.ActivityDateField;
            }
            set {
                if ((this.ActivityDateField.Equals(value) != true)) {
                    this.ActivityDateField = value;
                    this.RaisePropertyChanged("ActivityDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ActivityID {
            get {
                return this.ActivityIDField;
            }
            set {
                if ((this.ActivityIDField.Equals(value) != true)) {
                    this.ActivityIDField = value;
                    this.RaisePropertyChanged("ActivityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identifier {
            get {
                return this.IdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentifierField, value) != true)) {
                    this.IdentifierField = value;
                    this.RaisePropertyChanged("Identifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RA.IRecentActivityService")]
    public interface IRecentActivityService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecentActivityService/GetRecentlyAddedItems", ReplyAction="http://tempuri.org/IRecentActivityService/GetRecentlyAddedItemsResponse")]
        SOA.Framework.RA.RecentActivity[] GetRecentlyAddedItems(out int totalItemsCount, string mfbCode, long userID, string dataType, string applicationName, int page, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecentActivityService/GetRecentlyModifiedItems", ReplyAction="http://tempuri.org/IRecentActivityService/GetRecentlyModifiedItemsResponse")]
        SOA.Framework.RA.RecentActivity[] GetRecentlyModifiedItems(out int totalItemsCount, string mfbCode, long userID, string dataType, string applicationName, int page, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecentActivityService/GetRecentlyDeletedItems", ReplyAction="http://tempuri.org/IRecentActivityService/GetRecentlyDeletedItemsResponse")]
        SOA.Framework.RA.RecentActivity[] GetRecentlyDeletedItems(out int totalItemsCount, string mfbCode, long userID, string dataType, string applicationName, int page, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecentActivityService/GetRecentItems", ReplyAction="http://tempuri.org/IRecentActivityService/GetRecentItemsResponse")]
        SOA.Framework.RA.RecentActivity[] GetRecentItems(out int totalItemsCount, string mfbCode, long userID, string dataType, string applicationName, int page, int pageSize);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRecentActivityServiceChannel : SOA.Framework.RA.IRecentActivityService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecentActivityServiceClient : System.ServiceModel.ClientBase<SOA.Framework.RA.IRecentActivityService>, SOA.Framework.RA.IRecentActivityService {
        
        public RecentActivityServiceClient() {
        }
        
        public RecentActivityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecentActivityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecentActivityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecentActivityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOA.Framework.RA.RecentActivity[] GetRecentlyAddedItems(out int totalItemsCount, string mfbCode, long userID, string dataType, string applicationName, int page, int pageSize) {
            return base.Channel.GetRecentlyAddedItems(out totalItemsCount, mfbCode, userID, dataType, applicationName, page, pageSize);
        }
        
        public SOA.Framework.RA.RecentActivity[] GetRecentlyModifiedItems(out int totalItemsCount, string mfbCode, long userID, string dataType, string applicationName, int page, int pageSize) {
            return base.Channel.GetRecentlyModifiedItems(out totalItemsCount, mfbCode, userID, dataType, applicationName, page, pageSize);
        }
        
        public SOA.Framework.RA.RecentActivity[] GetRecentlyDeletedItems(out int totalItemsCount, string mfbCode, long userID, string dataType, string applicationName, int page, int pageSize) {
            return base.Channel.GetRecentlyDeletedItems(out totalItemsCount, mfbCode, userID, dataType, applicationName, page, pageSize);
        }
        
        public SOA.Framework.RA.RecentActivity[] GetRecentItems(out int totalItemsCount, string mfbCode, long userID, string dataType, string applicationName, int page, int pageSize) {
            return base.Channel.GetRecentItems(out totalItemsCount, mfbCode, userID, dataType, applicationName, page, pageSize);
        }
    }
}
